# Generated by Django 5.2.15 on 2026-07-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerskill',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_skills', to='providers.providerprofile'),
        ),
        migrations.AlterField(
            model_name='providerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_skills', to='providers.skill'),
        ),
    ]
